### PR TITLE
Do not forcibly remove the spark properties

### PR DESCRIPTION
**Pull request by lpinca**
I think it's better to let the GC do its job here.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
But *are* these properties really GC'd if these references are not removed?

**Comment by lpinca** [comment]
If they aren't there is a bug and we should fix it. Also doesn't make much sense to remove only some of them.

**Comment by lpinca** [comment]
IIRC we added that forced cleanup because people were complaining about memory leaks when using`primus-rooms`. I guess the problem was, and still is, in `primus-rooms`.

**Comment by lpinca** [comment]
@3rd-Eden yay or nay?

**Comment by 3rd-Eden** [comment]
Yay

**Pull request merged**
