### PR TITLE
Correctly expose the Primus constructor

### PR DESCRIPTION
**Pull request by lpinca**
This should correctly expose the constructor in the browser.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Thanks sir!

**Comment by STRML** [comment]
This appears to break plugins. For example, with primus-multiplex:

```javascript
// ...
},{"demolish":1,"emits":2,"eventemitter3":3,"querystringify":4,"recovery":5,"tick-tock":8}]},{},[10])(10)
});sandbox["Primus"].prototype.ark["multiplex"] = function client(primus) {

  // multiplex instance.
  var multiplex = new Primus.$.multiplex.Multiplex(primus);
```

`Primus` is undefined here.

**Comment by lpinca** [comment]
It seems to work fine here, it should grab the globally defined `Primus` [here](https://github.com/primus/primus/blob/2f02c6592c9d2ada6fd5a4ed5a4d5dfa4fcaaba2/index.js#L541).

**Comment by lpinca** [comment]
Anyway we should probably wrap the client side part of the plugins in yet another wrapper, like we do for the [libraries](https://github.com/primus/primus/blob/2f02c6592c9d2ada6fd5a4ed5a4d5dfa4fcaaba2/index.js#L613-L615), to avoid problems when the constructor is exposed with a different name.

This is getting kinda messy.

**Pull request merged**
