### PR TITLE
updated primus.d.ts

### PR DESCRIPTION
**Pull request by lholznagel**
Like discussed in #536 here is a typescript definition upgrade.

I just started with primus, so there could be some more changes needed.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
I don't have the TypeScript knowledge to review this PR. So can't really comment if the changes are valid or not.

**Comment by lpinca** [comment]
@lholznagel I've asked you to open this PR but I'm also not really qualified to review this, sorry.
We can assume that these definitions are correct and merge this or ask if someone from the community can help.

Maybe this PR can be changed to get rid of the definitions file instead?

**Comment by lpinca** [comment]
cc:  @dercodebearer @japhar81

**Comment by lholznagel** [comment]
That would be a good idea.

**Comment by lpinca** [comment]
@lholznagel there a bunch of issues in the definitions file like wrong method names (`before` -> `use`, `use` -> `plugin`, etc.) wrong return values, wrong types (`req` is almost all cases an instance of `http.IncomingMessage`) etc.

I would change this PR and make it remove the file. People interested in TypeScript definitions for Primus should rely on DefinitelyTyped.

**Comment by lholznagel** [comment]
I mostly copied the old on to this one.

So, update the PR to remove the definition file and open a PR https://github.com/DefinitelyTyped/DefinitelyTyped?
There of course with the right returns.

**Comment by lpinca** [comment]
@lholznagel yes thanks! and I know you based this on the old file, not your fault at all!

**Comment by lholznagel** [comment]
Phew! :)

I can take a look at the current code and try to reproduce this in a definition file.

**Comment by lpinca** [comment]
That sounds great. Thank you so much, if you need anything just ask. We are also on IRC, irc.freenode.net #primus channel.

**Comment by lholznagel** [comment]
Did some work today in [another branch](/lholznagel/primus/tree/update-definition). Think I covered everything. Will test tomorrow and see if it matches the documentation examples.

Also: great documentation! Code and Readme side! really helped.

**Comment by lpinca** [comment]
@lholznagel Any update?

**Comment by lholznagel** [comment]
Sorry for the delay, I started testing. The tests looked pretty good. Will try to finish this in the course of this week.

**Comment by lpinca** [comment]
No problem, thanks.

**Comment by xiamx** [comment]
I think we should keep the definitions in this repo. Please take a look at @blakeembrey 's comment on https://github.com/vitaly-t/pg-promise/issues/220#issuecomment-260165225 for a discussion on a similar scenario. If you guys need a hand on reviewing typescript related PRs I can help.

**Comment by lholznagel** [comment]
@xiamx so you mean just add the definition to the package.json as `"typings": "primus.d.ts"`?

**Comment by blakeembrey** [comment]
@lholznagel Yes, that's all that's needed after the file has been refactored into external module format.

**Comment by xiamx** [comment]
@lholznagel Yes that's exactly it. 

And although having it community-maintained is definitely an option, first-party support will give the definition file some more visibility. Moreover, it appears that @lholznagel has shown interests and skill required to maintain this file. 

👍 for merging

**Comment by lpinca** [comment]
> Of course, it's really up to the maintainers if they want to have the definition in the project or would prefer the community maintain it on DefinitelyTyped.

We don't use TypeScript so there will not be any update to the definition file from us (maintainers). Moving it to DefinitelyTyped is still better imo as it ensures that changes are reviewed and acknowledged by TypeScript users. The only downside is the additional `npm install` step mentioned by @blakeembrey, but I guess it is not uncommon in TypeScript world.

I am still inclined to move the definition to DefinitelyTyped but if Primus users prefer to have the definition in the project, that's fine (again there will not be any update from us).

**Comment by lholznagel** [comment]
I started testing in this repo:
https://github.com/lholznagel/primus-test

I am reproducing all example in the readme. Currently, I working at the browser section

**Comment by xiamx** [comment]
The TypeScript definition updates in DefinitelyTyped are not always comfortable, and in a few times, chaotic. Inexperienced contributors would submit pull-request of their untested changes (for features that they don't even use.) It would be fantastic for Primus TypeScript users to have the `d.ts` file in this primary repo. It's okay if the `d.ts` file won't be updated by the current maintainers, as long as you guys are open for pull requests (and maybe summoning @lholznagel and whoever that worked on this to review the changes).

Making my best attempt here to convince you guys, but at the end of the day it's up to the maintainers to decide. 😃

**Comment by blakeembrey** [comment]
I'll throw in and say that in the current state, DefinitelyTyped makes it incredibly hard to maintain a definition. The people reviewing definitions may not use the project or be associated with it, and the people interested in contributing may be deterred by the hundred of existing PRs to other definitions or just can't subscribe to catch changes because you can't have that fine grained control (hence, just unsubscribing altogether). Overall, as a non-TypeScript user and maintainer, the best approach may be to keep it with the repo until https://github.com/Microsoft/types-publisher/issues/4 allows you to have "official" definitions where you can add TypeScript contributors like @lholznagel.

I would certainly be interested in knowing which approach makes you most comfortable as it's a situation I'm invested on improving for regular package authors. The more type information and documentation we can get in the TypeScript community, the better it'll be 😄

**Comment by lpinca** [comment]
Ok convinced, the definition file can stay.

**Comment by 3rd-Eden** [comment]
In that case, this PR can be merged.

**Comment by 3rd-Eden** [comment]
Thanks for the contributions and the insights <3

**Comment by lpinca** [comment]
@3rd-Eden there were quite a few things to fix, but hopefully @lholznagel will send a new PR from his other [branch](https://github.com/lholznagel/primus/commit/a869de21a3e77292760e30336e6ac1aa9a658ef9) :)

**Comment by 3rd-Eden** [comment]
RIP.

**Comment by lholznagel** [comment]
yep, this was not done :/

Will do another pr when I am done :)

**Pull request merged**
