### PR TITLE
Updating the type definition file.

### PR DESCRIPTION
**Pull request by dercodebearer**
Updated the TypeDefinition file to not throw implicit any errors, and also resolved duplicate namespacing issue.

### CODE REVIEW

**Comment by dercodebearer** [comment]
May I also post this to the definitely typed repo after it's been merged?

**Comment by dercodebearer** [comment]
Resolves issue #436

**Comment by dercodebearer** [comment]
@japhar81 , since you're the original one who created this file, please let me know if this looks okay. Additionally, for ease of access, I'm setting up a typings registry for this. I'm adding you as one of the contributors to the file as a comment at the beginning of the file.

**Comment by japhar81** [comment]
@dercodebearer LGTM

**Comment by lpinca** [comment]
I think that the TypeScript kung-fu is weak among Primus team members, so I guess we can only trust you guys.

@dercodebearer I'm ok with you posting this on the definitely typed repo, so if @3rd-Eden has no objections go ahead.

**Comment by dercodebearer** [comment]
Perfect! Thanks @japhar81 and @lpinca . I've issued a PR to the Typings repo. I think there'll be some back and forth there, so I'll keep you posted of updates. Unless @3rd-Eden has any issues, I'll keep chugging along with it.

**Comment by 3rd-Eden** [comment]
Go a head, pull requests are encouraged here as we have no idea what we're talking about :dancer:

**Pull request merged**
