### PR TITLE
Add socket parameter in Spark constructor wrapper

### PR DESCRIPTION
**Pull request by kinsi55**
Just finally got around to change my proprietary rooms plugin implementation to one I could actually release and realized I failed to add the new socket variable introduced w/ #703 here, thus it always ending up "undefined". Oops, should've tested in advance, sorry!

### CODE REVIEW

**Comment by lpinca** [comment]
Can you please add a regression test?

**Comment by kinsi55** [comment]
I'd be lying if I said yes, but I can try.

**Comment by lpinca** [comment]
We also forgot to document the new property, if you can please also add it in the README.

**Comment by kinsi55** [comment]
Not gonna lie I hardly ever work with tests, how are entirely unrelated tests failing now because of my added one 😕

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
