### PR TITLE
Stop deferring the events on the client

### PR DESCRIPTION
**Pull request by lpinca**
This is a breaking and maybe unwanted change.
It fixes some open issues (#320, #263, #264) and possible race conditions.

It removes a [workaround](https://gist.github.com/mloughran/2052006) used to prevent iOS 5 from crashing under certain circumstances.

In short it's a f**k you to the users of iOS 5, but I would give a stable and bug free library to the majority of the users rather than a buggy one to everyone.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
:+1: but the pull request is on hold until we're about to release 5.0 as I don't want any breaking changes in master just yet.

**Comment by sudpaw** [comment]
Hi, Whats the ETA on this?

**Comment by jcrugzz** [comment]
This seems reasonable. There can't be very many if ANY users on iOS 5 due to apples upgrade pipeline.

**Comment by 3rd-Eden** [comment]
ETA is now.

**Comment by sudpaw** [comment]
Awesome!

**Pull request merged**
