### PR TITLE
[fix] Set client-store-expire option to 0 for socket.io

### LINKED ISSUE #330: Primus should set client store expiration to 0 for socket.io
Consider the following code:

```js
'use strict';

var Primus = require('primus');
var primus = Primus.createServer({
  transformer: 'socket.io',
  port: 8080
});

var socket = new primus.Socket('http://localhost:8080');

setTimeout(function () {
  socket.end();
  primus.destroy();
}, 1000);

```

This code will run an extra 15 seconds by default due to the `client store expiration` setting in `socket.io`.

If we were to use a different transformer, `engine.io` for example, the script would exit without the 15 second wait.

Since the goal of Primus is to abstract differences between real-time modules, we should set `client store expiration` to 0 for a consistent experience between transformers.

### PR DESCRIPTION
**Pull request by jgrund**
Fixes #330.

Signed-off-by: Joe Grund <grundjoseph@gmail.com>

### CODE REVIEW

**Comment by lpinca** [comment]
Thank you!

**Comment by 3rd-Eden** [comment]
Nice find, thanks for the patch!

**Comment by jgrund** [comment]
Thanks! When will this end up in a release?

**Comment by lpinca** [comment]
@jgrund the next release will be `Primus@3.0.0`.
We are working to make browserify work with our client.
That shouldn't take much time as we already have a good progress.

**Pull request merged**
