### PR TITLE
Fix compatibility with uws 0.10.x

### PR DESCRIPTION
**Pull request by lpinca**
This updates the uws transformer to make it work with `uws@0.10.x`.
The `maxPayload` option seems to be ignored by the current version of `uws` so tests fail.

### CODE REVIEW

**Comment by SEAPUNK** [comment]
0.10.5 has been released; re-run the tests?

**Comment by lpinca** [comment]
@SEAPUNK the "maxPayload" is still not addressed https://github.com/uWebSockets/uWebSockets/compare/7baccde2...60986966. Test fails locally, no need to run CI.

**Comment by lpinca** [comment]
`uws@0.10.9` still ignores the `maxPayload` option but luckily, now messages bigger than 16 MiB are dropped. The connection is closed accordingly. We can't still support 0.10.x because:

1. Tests fail.
2. I see no way to send a message bigger than 16 MiB.

**Comment by SEAPUNK** [comment]
I'll try to look into it this weekend.

**Comment by SEAPUNK** [comment]
Quoting Alex,

> It's not broken. But it is 16mb hardcoded now.

**Comment by lpinca** [comment]
What's the point in doing this https://github.com/uWebSockets/uWebSockets/blob/0e523747ff5c6e29237e18541068ecdba877cd1c/nodejs/dist/uws.js#L330 then?
I think you can remove that as it doesn't matter if I specify 1KiB or 100MiB, it's always 16MiB.

If this is not going to change I'll update the transformer removing the `maxPayload` option as it is no longer needed and skip the test for `uws`.

Side note: How does one validates the benchmark for the "Huge message throughput" on uws?

**Comment by SEAPUNK** [comment]
I bet it's just some leftover code.

Not sure; right now I'm focused on cleaning up the nodejs module a bit, and adding tests to it and whatnot, but I'll keep these things in mind, and see what I can do about them.

**Comment by lpinca** [comment]
@SEAPUNK I would like to know if `maxPayload` is still an option or not. If the value is just hardcoded for the time being, there is no reason to keep the option in the Primus transformer as that will be only misleading for everyone reading the code.

**Comment by SEAPUNK** [comment]
I'll ask Alex.

**Comment by SEAPUNK** [comment]
I don't think anything regarding that is going to change soon, but I'll ask again sometime tomorrow.

**Pull request merged**
